image: node:latest

stages:
    - install
    - lint
    - test
    - build

cache:
  paths:
    - node_modules/

install:
    stage: install
    script:
        - npm install
        
lint:
    stage: lint
    script:
        - npm run lint
    
test:
    stage: test
    script:
        - npm run test
    coverage: All files[^|]*\|[^|]*\s+([\d\.]+)

build:
    stage: build
    script:
        - npm run build
    artifacts:
        paths:
        - build/
